services:
  # Main API service
  api:
    build:
      context: .
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  # React Frontend service
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8001
    depends_on:
      - api
    restart: unless-stopped

volumes:
  data:
    driver: local